export const EQUIPO_DEA = [
  'Nancy Neschuk',
  'Luis Bree',
  'Norma Bordón',
  'Gonzalo Castro',
  'Eugenia Agabios',
  'Alan Santamarina',
  'Canela Castro',
  'Cintia Di Grazia',
  'Mariano Mediavilla',
  'Marina Raggio',
  'Luciana Lugones',
  'Pablo Giner',
  'Vanina Kapeika',
  'Virginia Martínez Alcántara',
  'Luciana Landa',
  'María Ángeles González',
  'Celina Bertoni',
  'Ariel Menescardi',
  'Sandra Lafalce',
  'Andrea D´Emilio',
  'Carolina Silva',
  'Joaquín Montorsi',
].sort((a, b) => a.localeCompare(b));

export const EQUIPO_SIG = [
  'Luis Bree',
  'Cintia Di Grazia',
  'María Ángeles González',
  'Alan Santamarina',
].sort((a, b) => a.localeCompare(b));
